server:
  port: 8082

spring:
  application:
    name: authorization
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/authzdb?authSource=admin
kafka:
  tunnel:
    group: tunnel
  bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
  topic:
    producer: topic-sub
    consumer: topic-pub
