apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      containers:
      - name: authorization
        image: i50729/cp-authorization
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: authorization
  type: NodePort