apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gatewayapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapp
  template:
    metadata:
      labels:
        app: gatewayapp
    spec:
      containers:
      - name: gatewayapp
        image: i50729/cp-apigateway
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gatewayapp
  labels:
    app: gatewayapp
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30008
  selector:
    app: gatewayapp
