/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cp.chargeotg.mq;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AuthorizationCheckEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4326850359166932665L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AuthorizationCheckEvent\",\"namespace\":\"cp.chargeotg.mq\",\"fields\":[{\"name\":\"stationId\",\"type\":\"string\"},{\"name\":\"driverToken\",\"type\":\"string\"},{\"name\":\"callbackUrl\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AuthorizationCheckEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AuthorizationCheckEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AuthorizationCheckEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AuthorizationCheckEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AuthorizationCheckEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AuthorizationCheckEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AuthorizationCheckEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AuthorizationCheckEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AuthorizationCheckEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence stationId;
  private java.lang.CharSequence driverToken;
  private java.lang.CharSequence callbackUrl;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AuthorizationCheckEvent() {}

  /**
   * All-args constructor.
   * @param stationId The new value for stationId
   * @param driverToken The new value for driverToken
   * @param callbackUrl The new value for callbackUrl
   */
  public AuthorizationCheckEvent(java.lang.CharSequence stationId, java.lang.CharSequence driverToken, java.lang.CharSequence callbackUrl) {
    this.stationId = stationId;
    this.driverToken = driverToken;
    this.callbackUrl = callbackUrl;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationId;
    case 1: return driverToken;
    case 2: return callbackUrl;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationId = (java.lang.CharSequence)value$; break;
    case 1: driverToken = (java.lang.CharSequence)value$; break;
    case 2: callbackUrl = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'stationId' field.
   * @return The value of the 'stationId' field.
   */
  public java.lang.CharSequence getStationId() {
    return stationId;
  }


  /**
   * Sets the value of the 'stationId' field.
   * @param value the value to set.
   */
  public void setStationId(java.lang.CharSequence value) {
    this.stationId = value;
  }

  /**
   * Gets the value of the 'driverToken' field.
   * @return The value of the 'driverToken' field.
   */
  public java.lang.CharSequence getDriverToken() {
    return driverToken;
  }


  /**
   * Sets the value of the 'driverToken' field.
   * @param value the value to set.
   */
  public void setDriverToken(java.lang.CharSequence value) {
    this.driverToken = value;
  }

  /**
   * Gets the value of the 'callbackUrl' field.
   * @return The value of the 'callbackUrl' field.
   */
  public java.lang.CharSequence getCallbackUrl() {
    return callbackUrl;
  }


  /**
   * Sets the value of the 'callbackUrl' field.
   * @param value the value to set.
   */
  public void setCallbackUrl(java.lang.CharSequence value) {
    this.callbackUrl = value;
  }

  /**
   * Creates a new AuthorizationCheckEvent RecordBuilder.
   * @return A new AuthorizationCheckEvent RecordBuilder
   */
  public static cp.chargeotg.mq.AuthorizationCheckEvent.Builder newBuilder() {
    return new cp.chargeotg.mq.AuthorizationCheckEvent.Builder();
  }

  /**
   * Creates a new AuthorizationCheckEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AuthorizationCheckEvent RecordBuilder
   */
  public static cp.chargeotg.mq.AuthorizationCheckEvent.Builder newBuilder(cp.chargeotg.mq.AuthorizationCheckEvent.Builder other) {
    if (other == null) {
      return new cp.chargeotg.mq.AuthorizationCheckEvent.Builder();
    } else {
      return new cp.chargeotg.mq.AuthorizationCheckEvent.Builder(other);
    }
  }

  /**
   * Creates a new AuthorizationCheckEvent RecordBuilder by copying an existing AuthorizationCheckEvent instance.
   * @param other The existing instance to copy.
   * @return A new AuthorizationCheckEvent RecordBuilder
   */
  public static cp.chargeotg.mq.AuthorizationCheckEvent.Builder newBuilder(cp.chargeotg.mq.AuthorizationCheckEvent other) {
    if (other == null) {
      return new cp.chargeotg.mq.AuthorizationCheckEvent.Builder();
    } else {
      return new cp.chargeotg.mq.AuthorizationCheckEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AuthorizationCheckEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AuthorizationCheckEvent>
    implements org.apache.avro.data.RecordBuilder<AuthorizationCheckEvent> {

    private java.lang.CharSequence stationId;
    private java.lang.CharSequence driverToken;
    private java.lang.CharSequence callbackUrl;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cp.chargeotg.mq.AuthorizationCheckEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.driverToken)) {
        this.driverToken = data().deepCopy(fields()[1].schema(), other.driverToken);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.callbackUrl)) {
        this.callbackUrl = data().deepCopy(fields()[2].schema(), other.callbackUrl);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AuthorizationCheckEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(cp.chargeotg.mq.AuthorizationCheckEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.driverToken)) {
        this.driverToken = data().deepCopy(fields()[1].schema(), other.driverToken);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.callbackUrl)) {
        this.callbackUrl = data().deepCopy(fields()[2].schema(), other.callbackUrl);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'stationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getStationId() {
      return stationId;
    }


    /**
      * Sets the value of the 'stationId' field.
      * @param value The value of 'stationId'.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder setStationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.stationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stationId' field has been set.
      * @return True if the 'stationId' field has been set, false otherwise.
      */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stationId' field.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder clearStationId() {
      stationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'driverToken' field.
      * @return The value.
      */
    public java.lang.CharSequence getDriverToken() {
      return driverToken;
    }


    /**
      * Sets the value of the 'driverToken' field.
      * @param value The value of 'driverToken'.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder setDriverToken(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.driverToken = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'driverToken' field has been set.
      * @return True if the 'driverToken' field has been set, false otherwise.
      */
    public boolean hasDriverToken() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'driverToken' field.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder clearDriverToken() {
      driverToken = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'callbackUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getCallbackUrl() {
      return callbackUrl;
    }


    /**
      * Sets the value of the 'callbackUrl' field.
      * @param value The value of 'callbackUrl'.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder setCallbackUrl(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.callbackUrl = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'callbackUrl' field has been set.
      * @return True if the 'callbackUrl' field has been set, false otherwise.
      */
    public boolean hasCallbackUrl() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'callbackUrl' field.
      * @return This builder.
      */
    public cp.chargeotg.mq.AuthorizationCheckEvent.Builder clearCallbackUrl() {
      callbackUrl = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AuthorizationCheckEvent build() {
      try {
        AuthorizationCheckEvent record = new AuthorizationCheckEvent();
        record.stationId = fieldSetFlags()[0] ? this.stationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.driverToken = fieldSetFlags()[1] ? this.driverToken : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.callbackUrl = fieldSetFlags()[2] ? this.callbackUrl : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AuthorizationCheckEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AuthorizationCheckEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AuthorizationCheckEvent>
    READER$ = (org.apache.avro.io.DatumReader<AuthorizationCheckEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.stationId);

    out.writeString(this.driverToken);

    out.writeString(this.callbackUrl);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.stationId = in.readString(this.stationId instanceof Utf8 ? (Utf8)this.stationId : null);

      this.driverToken = in.readString(this.driverToken instanceof Utf8 ? (Utf8)this.driverToken : null);

      this.callbackUrl = in.readString(this.callbackUrl instanceof Utf8 ? (Utf8)this.callbackUrl : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.stationId = in.readString(this.stationId instanceof Utf8 ? (Utf8)this.stationId : null);
          break;

        case 1:
          this.driverToken = in.readString(this.driverToken instanceof Utf8 ? (Utf8)this.driverToken : null);
          break;

        case 2:
          this.callbackUrl = in.readString(this.callbackUrl instanceof Utf8 ? (Utf8)this.callbackUrl : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










