server:
  port: 8080

spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092

kafka:
  tunnel:
    group: tunnelGroup
  bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092
  topic:
    producer: topic-pub
    consumer: topic-sub

autodash:
  connect:
    url: http://localhost:8084